name: auto comment
on: push
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install bs4
      - name: execute python script
        run: |
          python add_comment.py '${{ steps.file_changes.outputs.files_added }}'
      - name: add and commit
        uses: Endbug/add-and-commit@v7
        with:
          message: auto comment for '${{ steps.file_changes.outputs.files_added }}'
